name: Tauri Build & Release

on:
  push:
    branches: [ "main" ]   # change if your default branch is different
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write       # needed to create/upload releases
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            args: "--target aarch64-apple-darwin"
          - platform: macos-latest
            args: "--target x86_64-apple-darwin"
          - platform: ubuntu-22.04
            args: ""
          - platform: windows-latest
            args: ""

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: |
            tauri-app/pnpm-lock.yaml
            tauri-app/yarn.lock
            tauri-app/package-lock.json

      - name: Read version from tauri-app/package.json
        id: meta
        shell: bash
        run: |
          VER=$(node -p "require('./tauri-app/package.json').version || ''")
          if [ -z "$VER" ]; then
            echo "No version found in tauri-app/package.json"; exit 1
          fi
          echo "version=$VER" >> "$GITHUB_OUTPUT"

      - name: Skip if tag already exists
        id: checktag
        shell: bash
        run: |
          TAG="v${{ steps.meta.outputs.version }}"
          if git ls-remote --tags origin | grep -q "refs/tags/${TAG}$"; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install Linux build deps
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev \
            libappindicator3-dev librsvg2-dev patchelf

      # Install frontend deps inside tauri-app/
      - name: Install deps (pnpm)
        if: hashFiles('tauri-app/pnpm-lock.yaml') != ''
        run: |
          corepack enable
          cd tauri-app
          pnpm i --frozen-lockfile
      - name: Install deps (yarn)
        if: hashFiles('tauri-app/yarn.lock') != '' && hashFiles('tauri-app/pnpm-lock.yaml') == ''
        run: |
          corepack enable
          cd tauri-app
          yarn install --frozen-lockfile
      - name: Install deps (npm)
        if: hashFiles('tauri-app/pnpm-lock.yaml') == '' && hashFiles('tauri-app/yarn.lock') == ''
        run: |
          cd tauri-app
          npm ci

      - name: macOS signing preflight
        if: matrix.platform == 'macos-latest'
        shell: bash
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        run: |
          set -euo pipefail
          TMP=/tmp/cert.p12
          # decode (try both BSD and GNU base64 flags)
          (echo "$APPLE_CERTIFICATE" | base64 -D -o "$TMP") || (echo "$APPLE_CERTIFICATE" | base64 -d > "$TMP")
          # create and unlock a throwaway keychain
          security create-keychain -p "" build.keychain
          security set-keychain-settings build.keychain
          security list-keychains -d user -s build.keychain login.keychain
          security unlock-keychain -p "" build.keychain
          # import p12
          security import "$TMP" -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security
          # show available signing identities (should list Developer ID Application)
          security find-identity -v -p codesigning build.keychain


      - name: Build & upload (Windows/Linux)
        if: matrix.platform != 'macos-latest' && steps.checktag.outputs.exists == 'false'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: tauri-app
          tagName: v${{ steps.meta.outputs.version }}
          releaseName: v${{ steps.meta.outputs.version }}
          releaseBody: "Installers for macOS, Linux, and Windows are attached below."
          releaseDraft: false
          prerelease: ${{ contains(steps.meta.outputs.version, '-alpha') || contains(steps.meta.outputs.version, '-beta') || contains(steps.meta.outputs.version, '-rc') }}
          args: ${{ matrix.args }}


      - name: Build only (no release) because tag exists
        if: steps.checktag.outputs.exists == 'true'
        run: echo "Tag v${{ steps.meta.outputs.version }} already exists. Skipping release upload."



      # - name: Build & upload to GitHub Release
      #   if: steps.checktag.outputs.exists == 'false'
      #   uses: tauri-apps/tauri-action@v0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     projectPath: tauri-app
      #     tagName: v${{ steps.meta.outputs.version }}
      #     releaseName: v${{ steps.meta.outputs.version }}
      #     releaseBody: "Installers for macOS, Linux, and Windows are attached below."
      #     releaseDraft: false
      #     prerelease: ${{ contains(steps.meta.outputs.version, '-alpha') || contains(steps.meta.outputs.version, '-beta') || contains(steps.meta.outputs.version, '-rc') }}
      #     args: ${{ matrix.args }}
      # replace your current "Build & upload..." step with this pair